from __future__ import annotations

from pathlib import Path

import pandas as pd
import typer
from jinja2 import Template
from rich.console import Console

app = typer.Typer(help="Report generation.", no_args_is_help=True)
console = Console()

REPORT_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>MatScreen Report</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 960px; margin: 0 auto; padding: 40px 20px; color: #1a1a2e; }
h1 { color: #1565C0; }
table { width: 100%; border-collapse: collapse; margin: 20px 0; }
th, td { padding: 10px 14px; text-align: left; border-bottom: 1px solid #e2e8f0; }
th { background: #f1f5f9; font-weight: 600; }
.trust { color: #2E7D32; font-weight: 700; }
.verify { color: #E65100; font-weight: 700; }
.defer { color: #C62828; font-weight: 700; }
.summary { display: flex; gap: 40px; margin: 20px 0; }
.stat { text-align: center; }
.stat .number { font-size: 2rem; font-weight: 700; color: #1565C0; }
.stat .label { font-size: 0.9rem; color: #64748b; }
.toxic-flag { color: #C62828; font-size: 0.8rem; }
</style>
</head>
<body>
<h1>MatScreen Screening Report</h1>
<div class="summary">
<div class="stat"><div class="number">{{ total }}</div><div class="label">Candidates</div></div>
<div class="stat"><div class="number">{{ trust_count }}</div><div class="label">TRUST</div></div>
<div class="stat"><div class="number">{{ verify_count }}</div><div class="label">VERIFY</div></div>
<div class="stat"><div class="number">{{ defer_count }}</div><div class="label">DEFER</div></div>
</div>
<h2>Top Candidates</h2>
<table>
<tr>
<th>#</th><th>Formula</th><th>Triage</th><th>Band Gap (eV)</th>
<th>SQ Eff.</th><th>Uncertainty (eV)</th><th>Stability (eV/atom)</th><th>Abundance</th><th>Flags</th>
</tr>
{% for r in rows %}
<tr>
<td>{{ r.rank }}</td>
<td><strong>{{ r.formula }}</strong></td>
<td class="{{ r.triage }}">{{ r.triage|upper }}</td>
<td>{{ "%.2f"|format(r.band_gap) }}</td>
<td>{{ "%.1f%%"|format(r.sq_efficiency * 100) }}</td>
<td>{{ "%.3f"|format(r.bandgap_std) }}</td>
<td>{{ "%.3f"|format(r.ehull) }}</td>
<td>{{ "%.2f"|format(r.abundance) }}</td>
<td>{% if r.is_toxic %}<span class="toxic-flag">Toxic</span> {% endif %}{% if r.is_critical %}<span class="toxic-flag">Supply-critical</span>{% endif %}</td>
</tr>
{% endfor %}
</table>
<h2>DFT Verification Queue</h2>
{% if verify_rows %}
<p>{{ verify_rows|length }} materials require DFT verification before acting on predictions.</p>
<table>
<tr><th>Formula</th><th>Band Gap (eV)</th><th>SQ Eff.</th><th>Uncertainty (eV)</th></tr>
{% for r in verify_rows %}
<tr><td>{{ r.formula }}</td><td>{{ "%.2f"|format(r.band_gap) }}</td><td>{{ "%.1f%%"|format(r.sq_efficiency * 100) }}</td><td>{{ "%.3f"|format(r.bandgap_std) }}</td></tr>
{% endfor %}
</table>
{% else %}
<p>No materials in the VERIFY category.</p>
{% endif %}
<footer style="margin-top: 40px; color: #94a3b8; font-size: 0.85rem;">
Generated by MatScreen
</footer>
</body>
</html>
""")


@app.command()
def run(
    input_path: str = typer.Option("results/screening.json", help="Screening results path."),
    fmt: str = typer.Option("html", help="Output format (html, json)."),
    output: str = typer.Option("results/report.html", help="Output file path."),
) -> None:
    src = Path(input_path)
    if not src.exists():
        console.print(f"[red]No screening results at {src}. Run 'matscreen screen run' first.[/red]")
        raise typer.Exit(1)

    df = pd.read_json(src)
    console.print(f"[bold]Generating {fmt} report from {src} ({len(df)} candidates)[/bold]")

    out_path = Path(output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if fmt == "json":
        df.to_json(out_path, orient="records", indent=2)
        console.print(f"JSON report saved to {out_path}")
        return

    rows = []
    for i, (_, row) in enumerate(df.iterrows()):
        rows.append({
            "rank": row.get("pareto_rank", i + 1),
            "formula": row.get("formula", "?"),
            "triage": row.get("triage_label", "defer"),
            "band_gap": row.get("band_gap", 0),
            "sq_efficiency": row.get("sq_efficiency", 0),
            "bandgap_std": row.get("bandgap_std", 0),
            "ehull": row.get("energy_above_hull", 0),
            "abundance": row.get("abundance_score", 0),
            "is_toxic": row.get("is_toxic", False),
            "is_critical": row.get("is_critical", False),
        })

    verify_rows = [r for r in rows if r["triage"] == "verify"]

    html = REPORT_TEMPLATE.render(
        total=len(rows),
        trust_count=sum(1 for r in rows if r["triage"] == "trust"),
        verify_count=len(verify_rows),
        defer_count=sum(1 for r in rows if r["triage"] == "defer"),
        rows=rows,
        verify_rows=verify_rows,
    )

    out_path.write_text(html)
    console.print(f"HTML report saved to {out_path}")
